backend:
  branch: master # Branch to update (optional; defaults to master)
  name: github
  repo: ilikerobots/bd_vineyard
  #name: git-gateway

media_folder: "images" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Mandatory Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    name: "mandatory_pages"
    create: false
    delete: false
    files:
    - label: "Welcome"
      name: "index"
      file: "index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Layout, name: layout, widget: hidden, default: default}
        - {label: Callout, name: callout, widget: markdown}
        - {label: Callout CTA, name: callout_cta, widget: string}
        - {label: Callout CTA Link, name: callout_cta_link, widget: string}
        - {label: Callout Image 1, name: callout_img_1, widget: image}
        - {label: Callout Image 2, name: callout_img_2, widget: image}
        - {label: Body, name: body, widget: markdown}
        - label: Row Sections
          name: row_sections
          widget: list
          fields:
            - {label: Page Title, name: title, widget: string, required: true}
            - {label: Icon, name: icon, widget: string}
            - {label: Description, name: description, widget: markdown}
        - {label: Grid Intro, name: grid_intro, widget: string}
        - {label: Grid CTA, name: grid_cta, widget: string}
        - {label: Grid Link, name: grid_link, widget: string}
        - label: Grid Sections
          name: grid_sections
          widget: list
          fields:
            - {label: Page Title, name: title, widget: string}
            - {label: Description, name: description, widget: markdown}
            - {label: Image, name: img, widget: image}
            - {label: Link, name: link, widget: string}
        - {label: Main CTA Header, name: maincta_header, widget: string}
        - {label: Main CTA Text, name: maincta_text, widget: string}
        - {label: Main CTA Primary Button, name: maincta_btn_primary, widget: string}
        - {label: Main CTA Primary Button Link, name: maincta_btn_primary_link, widget: string}
        - {label: Main CTA Secondary Button, name: maincta_btn_secondary, widget: string}
        - {label: Main CTA Secondary Button Link, name: maincta_btn_secondary_link, widget: string}
  - label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    name: "pages" # Used in routes, e.g., /admin/collections/blog
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    displayFields: ["title", "header"]
    searchFields: ["title", "body"]
    fields:
      - {label: Title, name: title, widget: string, required: True}
      - {label: Header, name: header, widget: string, required: True}
      - {label: Permanent Link, name: permalink, widget: string,   pattern: [".*\\.html$", "Must be \"<something>.html\""], required:True }
      - {label: Body, name: body, widget: markdown, required: True}
      - {label: Pre-Body Intro, name: description, widget: markdown, required: False}
      - label: "Layout"
        name: "layout"
        widget: "select"
        required: "True"
        default: "no-sidebar"
        options: ["left-sidebar", "right-sidebar", "no-sidebar"]
      - {label: Icon, name: icon, widget: string,  default: fa-leaf, pattern: ["^fa\\-", "Must be fa-<something>. See https://faicons.com/"], required:True }
      - label: Sidebar Sections
        name: sidebar_sections
        widget: list
        required: false
        fields:
        - {label: Header, name: title, widget: string}
        - {label: Description, name: description, widget: markdown}
        - {label: CTA, name: cta, widget: string}
        - {label: Image, name: img, widget: image}
        - {label: Link, name: link, widget: string}
      - label: Row Sections
        name: row_sections
        widget: list
        required: false
        fields:
        - {label: Header, name: title, widget: string}
        - {label: Description, name: description, widget: markdown}
        - {label: CTA, name: cta, widget: string}
        - {label: Link, name: link, widget: string}
      - {label: Include In Nav, name: include_in_nav, widget: hidden, default: True}
  - label: "Blogs" # Used in the UI
    label_singular: "Blog" # Used in the UI, ie: "New Post"
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    displayFields: ["title", "header", "date"]
    searchFields: ["title", "body"]
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "no-sidebar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

